[tox]
envlist = py{312,313}
min_version = 4.0

[testenv]
passenv =
    CMAKE_BUILD_PARALLEL_LEVEL
extras = dev
commands =
    check-manifest
    pip install -v -e .
    flake8 --exclude .git,env,dist,build,third_party,.tox .
    pytest -s tests

[flake8]
exclude = .tox,*.egg,build,data,third_party
select = E,W,F
ignore = W503
per-file-ignores =
    __init__.py: F401

[check-manifest]
ignore =
    fasm/parser/tags.py
    fasm/parser/libparse_fasm.*
    third_party/antlr4/runtime/PHP
