[tox]
envlist = py{312,313}
min_version = 4.0

[testenv]
extras = dev
commands =
    pip install -v -e .
    flake8 --exclude .git,env,dist,build,third_party,.tox .
    pytest -s tests

[flake8]
exclude = .tox,*.egg,build,data,third_party
select = E,W,F
ignore = W503
max-line-length = 100
per-file-ignores =
    __init__.py: F401
