# Checks code that code meets requirements for a pull request.
# Any automated checks for code quality and compliance belongs here.
name: presubmit
on: [push, pull_request]
jobs:
  check:
    name: Source checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Python style check
        run: |
          make format lint
          test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
      - name: Check license
        run: make check-license
      - name: Python checks
        run: make check-python-scripts
  test:
    name: Test Python package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Tox
        run: tox -e py
