# Builds and tests a pure-Python wheel.
name: Python wheel
on: [push, pull_request]
jobs:
  wheel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip build
    - name: Build wheel
      run: python -m build
    - name: Test wheel installation
      run: |
        python -m pip install dist/*.whl pytest
        python -m pytest tests/
    - uses: actions/upload-artifact@v4
      with:
        name: fasm
        path: dist
